version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - cd TransunionMailImport && mvn package
      - mv target/TransunionMailImport-1.0.jar TransunionMailImport-1.0.jar
artifacts:
  files:
    - TransunionMailImport-1.0.jar
    - .ebextensions/**/*