version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  post_build:
    commands:
      - mvn package
      - mv target/TransunionMailImport.jar TransunionMailImport.jar
artifacts:
  files:
    - TransunionMailImport.jar
    - .ebextensions/**/*